# Generated by Django 4.2.16 on 2024-10-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Music', 'Music'), ('Sports', 'Sports'), ('Theatre', 'Theatre'), ('Dance', 'Dance'), ('Garba', 'Garba')], default='music', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='payment_options',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('UPI', 'UPI'), ('Cash', 'Cash')], max_length=255),
        ),
    ]
