# Generated by Django 4.2.16 on 2024-10-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('bengaluru', 'Bengaluru'), ('hyderabad', 'Hyderabad'), ('chennai', 'Chennai'), ('delhi', 'Delhi'), ('mumbai', 'Mumbai'), ('pune', 'Pune'), ('kolkata', 'Kolkata'), ('jaipur', 'Jaipur')], max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='payment_options',
            field=models.CharField(max_length=255),
        ),
    ]
