# Generated by Django 4.2.16 on 2024-10-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_booking_is_confirmed_booking_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_per_ticket',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
            preserve_default=False,
        ),
    ]
